version: '2'

services:
  app:
    container_name: app
    build: .
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '3000:3000'

  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'